In [19]:
from sklearn.datasets import load_wine
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

wine = load_wine()
wine_data = wine.data
wine_target = wine.target
df_wine = pd.DataFrame(data = wine_data, columns = wine.feature_names)
df_target = pd.DataFrame(data = wine.target, columns = ['target'])
df_wine.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [22]:
data=pd.concat([df_wine, df_target], axis=1)

In [37]:
#Splitting the data into training and test test
X = data.iloc[:,0:13].values
y = data.iloc[:,13].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

Y = pd.get_dummies(y1).values


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state=0) 

In [38]:
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [39]:
Y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1,

In [40]:
#Defining the model 

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam


model = Sequential()

model.add(Dense(10,input_shape=(13,),activation='tanh'))
model.add(Dense(8,activation='tanh'))
model.add(Dense(6,activation='tanh'))
model.add(Dense(3,activation='softmax'))

model.compile(Adam(lr=0.04),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 10)                140       
                                                                 
 dense_13 (Dense)            (None, 8)                 88        
                                                                 
 dense_14 (Dense)            (None, 6)                 54        
                                                                 
 dense_15 (Dense)            (None, 3)                 21        
                                                                 
Total params: 303
Trainable params: 303
Non-trainable params: 0
_________________________________________________________________


/Users/yes/opt/anaconda3/envs/aiclass/lib/python3.8/site-packages/keras/optimizers/optimizer_v2/adam.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [41]:
#fitting the model and predicting 

# fit network
model_history=model.fit(x=X_train, y=y_train, epochs=100, batch_size=13, validation_data= (X_test,y_test))
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/100
11/11 [==============================] - 1s 12ms/step - loss: 1.1602 - accuracy: 0.3028 - val_loss: 1.0595 - val_accuracy: 0.3889
Epoch 2/100
11/11 [==============================] - 0s 2ms/step - loss: 1.1186 - accuracy: 0.3380 - val_loss: 1.1162 - val_accuracy: 0.1667
Epoch 3/100
11/11 [==============================] - 0s 3ms/step - loss: 1.1360 - accuracy: 0.3169 - val_loss: 1.0436 - val_accuracy: 0.3889
Epoch 4/100
11/11 [==============================] - 0s 3ms/step - loss: 1.1039 - accuracy: 0.3099 - val_loss: 1.1271 - val_accuracy: 0.4444
Epoch 5/100
11/11 [==============================] - 0s 3ms/step - loss: 1.1157 - accuracy: 0.3380 - val_loss: 1.0438 - val_accuracy: 0.3889
Epoch 6/100
11/11 [==============================] - 0s 3ms/step - loss: 1.0997 - accuracy: 0.3662 - val_loss: 1.1145 - val_accuracy: 0.4444
Epoch 7/100
11/11 [==============================] - 0s 3ms/step - loss: 1.1223 - accuracy: 0.3873 - val_loss: 1.0671 - val_accuracy: 0.4444
Epoch 8/100


Epoch 59/100
11/11 [==============================] - 0s 3ms/step - loss: 1.1241 - accuracy: 0.2958 - val_loss: 1.0914 - val_accuracy: 0.4444
Epoch 60/100
11/11 [==============================] - 0s 3ms/step - loss: 1.1490 - accuracy: 0.3873 - val_loss: 1.0710 - val_accuracy: 0.4444
Epoch 61/100
11/11 [==============================] - 0s 3ms/step - loss: 1.1372 - accuracy: 0.2183 - val_loss: 1.0550 - val_accuracy: 0.4444
Epoch 62/100
11/11 [==============================] - 0s 3ms/step - loss: 1.1150 - accuracy: 0.3873 - val_loss: 1.0913 - val_accuracy: 0.4444
Epoch 63/100
11/11 [==============================] - 0s 3ms/step - loss: 1.1023 - accuracy: 0.3873 - val_loss: 1.0536 - val_accuracy: 0.4444
Epoch 64/100
11/11 [==============================] - 0s 3ms/step - loss: 1.1219 - accuracy: 0.3521 - val_loss: 1.0569 - val_accuracy: 0.4444
Epoch 65/100
11/11 [==============================] - 0s 3ms/step - loss: 1.1161 - accuracy: 0.3451 - val_loss: 1.0722 - val_accuracy: 0.3889
Epoch 

In [42]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        14
           1       0.44      1.00      0.62        16
           2       0.00      0.00      0.00         6

    accuracy                           0.44        36
   macro avg       0.15      0.33      0.21        36
weighted avg       0.20      0.44      0.27        36

[[ 0 14  0]
 [ 0 16  0]
 [ 0  6  0]]


/Users/yes/opt/anaconda3/envs/aiclass/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/yes/opt/anaconda3/envs/aiclass/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/yes/opt/anaconda3/envs/aiclass/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start,